### ISSUE TITLE
MP_INPUT_BUFFER_PADDING_SIZE is too small

### ISSUE THREAD

**Issue by ghost** [astiob/mplayer2#2]
when trying to build libmpdemux/demuxer.o it fails with this message, seems to be caused by FFMPEG updating their buffer padding size to 32

**Comment by astiob** [comment]
Thanks for the report! Could you please test the new [`ffmpeg` branch](https://github.com/astiob/mplayer2/tree/ffmpeg) and see if everything works there?

**Comment by ghost** [comment]
Yes that seems to have fixed the issue on my system with the new ffmpeg buffer size.

**Comment by astiob** [comment]
Thanks for confirming. I’ve merged this fix into the default branch `all`.
